spring:
    profiles:
        active: 
        - dev
---
server:
    port: 8201

spring:
    profiles: dev
    application:
        name: microservicecloud-config-client
eureka:
    client:
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/

---
server:
    port: 8202

spring:
    profiles: test
    application:
        name: microservicecloud-config-client
eureka:
    client:
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/


# 请保存为utf-8格式
# git@github.com:zdminglwy/microservicecloud-config.git